version: '2'

services:
  tilty:
    container_name: tilty
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./config:/etc/tilty
    command: -r --config-file /etc/tilty/config.ini
