name: Test

on:
  push:
    branches-ignore:
      - 'master'
      - 'refs/tags/*'
#on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}


    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: install pre-reqs
      run: sudo apt-get update && sudo apt-get install libbluetooth-dev && pip install -r requirements.txt && pip install -r requirements-dev.txt
    - name: isort
      run: isort -c -rc tilty -sp .
    - name: pylint
      run: pylint --rcfile .pylintrc -r n tilty
    - name: set pythonpath
      run: echo "::set-env name=PYTHONPATH::$(pwd)"
    - name: pytest
      run: py.test --cov-config .coveragerc --cov tilty --cov-report term-missing --cov-report xml --junitxml junit.xml tests
    - name: coveralls
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  clair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prep clair
        run: docker-compose -f docker-compose-clair.yml up -d
      - name: Download Clair-Scanner
        run: curl -Ls https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o clair-scanner && chmod +x clair-scanner
      - name: Build
        run: docker build -t myoung34/tilty:latest .
      - name: Test
        run: ./clair-scanner --ip $(ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+') myoung34/tilty:latest
